version: '3.2'
services:
  php7:
    image: library/php:7-cli-alpine
    volumes:
    - ./:/code
    working_dir: /code
  php8:
    image: gpsa/php:8.0.0alpha2
    build:
      context: ../docker
      args:
        NAME_BASE: alpine
        NAME_TAG: latest
    volumes:
    - ./:/code
    working_dir: /code